grammar:
    rule_list ignore_list

rule_list:
    rule_list rule
    | rule

rule:
    id ":" choice

choice:
    choice "|" sequence
    | sequence

sequence:
    sequence term
    | term

term:
    target primary multiplicity

target:
    id assignment_operator
    | %

assignment_operator:
    "="
    | "+="

multiplicity:
    "?" | "*" | "+" | %

primary:
    id
    | string
    | range
    | regexp
    | "(" choice ")"

id:
    /[a-zA-Z0-9_]+/

string:
    /"([^"\\]|\\.)+"/

range:
    /\[([^\]\\]|\\.)+\]/
    | "."

regexp:
    /\/([^\/\\]|\\.)+\//

ignore_list:
    ignore_list ignore_def
    | %

ignore_def:
    "~" ignore_term

ignore_term:
    string
    | range
    | regexp

~ /[ \r\n\t]+/
~ /\/\/.*$/m
~ /\/\*([^*]|\*+[^*\/])*\*+\//
