grammar:
    rule_list

rule_list:
    rule_list rule
    | rule

rule:
    id ":" choice

choice:
    choice "|" sequence
    | sequence

sequence:
    sequence term
    | term

term:
    target primary multiplicity_opt

target:
    id assignment_operator
    | %

multiplicity_opt:
    multiplicity
    | "++" primary
    | %

primary:
    id
    | string
    | range
    | "(" choice ")"
