
main:
    token=(string | number | keyword | delim | ignore)

string:
    "\"" char* "\""

char:
    [^"\\]
    | "\\" ["\\/bfnrt]
    | "\\u" hex hex hex hex

hex:
    [0-9a-fA-F]

number:
    int frac? exp?

int:
    "-"? ([0-9] | [1-9] [0-9]+)

frac:
    "." [0-9]+

exp:
    [eE] [+-]? [0-9]+

keyword:
    "true" | "false" | "null"

delim:
    [{}[\],:]

ignore:
    [ \r\n\t]
