start:
    _ body=expr _

expr:
    first=term operations+=(_ operator=[+-] _ operand=term)*

term:
    first=primary operations+=(_ operator=[*/] _ operand=primary)*

primary:
    value=int
    | "(" value=start ")"

int:
    [0-9]+

_:
    [ \r\n\t]*
