start:
    _ body=expr _

expr:
    operands+=term++(_ operators+=[+-] _)

term:
    operands+=primary++(_ operators+=[*/])

primary:
    value=int
    | "(" value=start ")"

int:
    [0-9]+

_:
    [ \r\n\t]*
